<a href="https://colab.research.google.com/github/alfonsoayalapaloma/etl/blob/main/02/ETL101_lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# üß≠ Taller: Exploradores de Datos Corporativos

Mision: Has sido seleccionado para consultar info la base de datos sqlite3 "banco.db"

Debes usar SQL para realizar las consultas.

In [6]:
import pandas as pd
import sqlite3
import requests
from io import StringIO

DB_NAME="banco.db"


def corre_sql( sql_text):
  conn = sqlite3.connect(DB_NAME)
  df_select = pd.read_sql_query(sql_text, conn)
  return df_select

In [7]:
corre_sql("select * from empleado")

     id_empleado  nombre  edad         cargo  salario  id_area
0              1   Sof√≠a    29     Asistente  5102.27        2
1              2    Luis    27      Analista  2546.70        4
2              3   Jorge    44       Gerente  4987.93        7
3              4   Sof√≠a    57  Especialista  2524.54        5
4              5   Luc√≠a    36     Asistente  6376.96        3
..           ...     ...   ...           ...      ...      ...
195          196     Ana    40   Coordinador  3313.63        3
196          197  Miguel    37      Analista  7963.88        4
197          198  Carlos    49  Especialista  7627.78       10
198          199   Laura    45     Ejecutivo  2948.20        3
199          200   Sof√≠a    39  Especialista  5875.16        1

[200 rows x 6 columns]